os:
  - linux

language: php

php:
  - '7.2'

addons:
  sonarcloud:
    organization: "assoconnect"

before_script:
  - composer self-update
  - composer install --no-interaction
  - composer require php-coveralls/php-coveralls
  - wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  
script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
  - php phpcs.phar --standard=PSR12 --ignore=/vendor/* ./
  - cat ./tests/logs/clover.xml
  - sonar-scanner

after_script:
  - vendor/bin/php-coveralls -v
